"""
TYSD Show Class, parent of Seasons
Currently not used a lot, will consider removing
"""

from __future__ import annotations
import os
from typing import TYPE_CHECKING, List
from pydantic import BaseModel, Field

from tvsd.config import settings

if TYPE_CHECKING:
    from tvsd.types.season import Season


class Show(BaseModel):
    """Represents a TV show.

    Attributes:
        title (str): The title of the show.
        begin_year (str): The year the show began.
        seasons (List[Season]): The seasons of the show.
        prefix (str): The directory name of the show.
    """

    title: str
    # source: "Source"
    begin_year: str
    seasons: List[Season] = Field(default_factory=list)

    @property
    def seasons(self) -> List["Season"]:
        """Returns a list of all the seasons of the show.

        Returns:
            List[Season]: A list of all the seasons of the show.
        """
        return self._seasons

    @property
    def prefix(self) -> str:
        """Generate the prefix for the show.

        The prefix is the directory name of the show, and is generated by combining the show's title and beginning year.

        Returns:
            str: The prefix for the show.
        """

        show_title = self.title.partition(" 第")[0]

        show_prefix: str = show_title + " (" + str(self.begin_year) + ")"
        return show_prefix

    # @property
    # def source(self) -> str:
    #     """Getter method for the source of the current Show.

    #     Returns:
    #         str: The source of the current Show.
    #     """
    #     return self._source.source_name

    @property
    def relative_show_dir(self) -> str:
        """Get the relative directory of the show in the media directory from the base path.

        This method returns the relative directory of the show in the media directory from the base path.

        Returns:
            str: The relative directory of the show in the media directory from the base path.
        """

        # Relative directory of show in media directory from base path
        return os.path.join(settings.SERIES_DIR, self.prefix)
