# Generated by Django 5.1.6 on 2025-03-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tvsd_ui", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchsession",
            name="sources",
            field=models.JSONField(default=list),
        ),
    ]
