"""
Django settings for tvsd_web project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from typing import Any

from tvsd.config import settings as tvsd_settings

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR: Path = Path(__file__).resolve().parent.parent


# Application definition

INSTALLED_APPS: list[str] = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "whitenoise.runserver_nostatic",
    "django.contrib.staticfiles",
    "django_simple_bulma",
    "crispy_forms",
    "crispy_bulma",
    "tvsd_ui",
    "django_unicorn",
]

MIDDLEWARE: list[str] = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "tvsd_web.urls"

TEMPLATES: list[dict[str, Any]] = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "tvsd_web.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES: dict[str, Any] = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS: list[dict[str, str]] = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/


ALLOWED_HOSTS: list[Any] = ["localhost", "127.0.0.1"]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Hong_Kong"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_DIRS = [
    BASE_DIR / "static",
    BASE_DIR / "_vendor",  # Files generated from gulp
]


# STORAGES = {
#     "staticfiles": {
#         "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
#     },
# }
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


STATICFILES_FINDERS: list[str] = [
    # First add the two default Finders, since this will overwrite the default.
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
    # Now add our custom SimpleBulma one.
    "django_simple_bulma.finders.SimpleBulmaFinder",
]


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Import TVSD settings
TVSD_SETTINGS = tvsd_settings


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    # "handlers": {
    #     "console": {
    #         "class": "logging.StreamHandler",
    #     },
    #     "file": {
    #         "class": "logging.FileHandler",
    #         "filename": "tvsd_web.log",
    #     },
    # },
    # "root": {
    #     "handlers": ["console", "file"],
    #     "level": "INFO",
    # },
    # "loggers": {
    #     "django": {
    #         "handlers": ["console", "file"],
    #         "level": "INFO",
    #         "propagate": False,
    #     },
    # },
}

# ----------------------------------- Bulma ---------------------------------- #

# Custom settings for django-simple-bulma
BULMA_SETTINGS: dict[str, Any] = {
    "extensions": ["bulma-navbar-burger", "bulma-divider"],
    # "variables": {
    #     "primary": "#000000",
    #     "size-1": "6rem",
    # },
    # "alt_variables": {
    #     "primary": "#fff",
    #     "scheme-main": "#000",
    # },
    "output_style": "compressed",  # production
    # "output_style": "expanded",
    # "fontawesome_token": "e761a01be3",
}

CRISPY_ALLOWED_TEMPLATE_PACKS = "bulma"

CRISPY_TEMPLATE_PACK = "bulma"


# ---------------------------------- Unicorn --------------------------------- #

# Django Unicorn settings
UNICORN: dict[str, Any] = {
    #     "APPS": [
    #         "unicorn",
    #         "pages",
    #     ],
    "MORPHER": {
        "NAME": "alpine",
    },
}


# --------------------------------- Dynaconf --------------------------------- #

# HERE STARTS DYNACONF EXTENSION LOAD (Keep at the very bottom of settings.py)
# Read more at https://www.dynaconf.com/django/
import dynaconf  # noqa

settings: dynaconf.LazySettings = dynaconf.DjangoDynaconf(
    __name__,
    PRELOAD_FOR_DYNACONF=[
        BASE_DIR / "settings.yaml",
        BASE_DIR / ".secrets.yaml",
        # "tvsd_ui.settings",
    ],
    # ENVVAR_PREFIX_FOR_DYNACONF="TVSD",
    ENV_SWITCHER_FOR_DYNACONF="TVSD_ENV",
    # SETTINGS_FILE_FOR_DYNACONF=BASE_DIR / "settings.yaml",
    # ENVVAR_FOR_DYNACONF="TVSD_SETTINGS",
    # INCLUDES_FOR_DYNACONF=[BASE_DIR / "plugins/*"],
)  # noqa
# HERE ENDS DYNACONF EXTENSION LOAD (No more code below this line)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = settings.SECRET_KEY

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = settings.DEBUG
